reservacion:
    pattern:  /
    defaults: { _controller: "CSEReservacionesBundle:Reservacion:index" }

reservacion_show:
    pattern:  /{id}/show
    defaults: { _controller: "CSEReservacionesBundle:Reservacion:show" }

reservacion_new:
    pattern:  /new
    defaults: { _controller: "CSEReservacionesBundle:Reservacion:new" }

reservacion_create:
    pattern:  /create
    defaults: { _controller: "CSEReservacionesBundle:Reservacion:create" }
    requirements: { _method: post }

reservacion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CSEReservacionesBundle:Reservacion:edit" }

reservacion_update:
    pattern:  /{id}/update
    defaults: { _controller: "CSEReservacionesBundle:Reservacion:update" }
    requirements: { _method: post|put }

reservacion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CSEReservacionesBundle:Reservacion:delete" }
    requirements: { _method: get }

reservacion_add_actividades:
    pattern:  /{id}/addActividades
    defaults: { _controller: "CSEReservacionesBundle:Reservacion:addActividades" }


reservacion_save_actividades:
    pattern:  /{id}/saveActividades
    defaults: { _controller: "CSEReservacionesBundle:Reservacion:saveActividades" }    
    
reservacion_servicios:
    pattern: /{id}/servicios
    defaults: {_controller: "CSEReservacionesBundle:Reservacion:servicios"}
    
reservacion_agregarservicios:
    pattern: /{id}/agregarServicios
    defaults: {_controller: "CSEReservacionesBundle:Reservacion:agregarServicios"}
    
reservacion_buscar:
    pattern: /buscar_Reservacion
    defaults: {_controller: "CSEReservacionesBundle:Reservacion:buscar"}
    
reservacion_reservaciones:
    pattern: /reporte_reservaciones
    defaults: {_controller: "CSEReservacionesBundle:Reservacion:reporteReservaciones"}

reservacion_ganancias:
    pattern: /reporte_ganancias
    defaults: {_controller: "CSEReservacionesBundle:Reservacion:reporteGanancias"}
    
reservacion_enviarEmail:
    pattern: /{id}/enviar_Email 
    defaults: {_controller: "CSEReservacionesBundle:Reservacion:envioReservacion"}
    
reservacion_enviarReporteReservaciones:
    pattern: /enviar_reporte_reservaciones 
    defaults: {_controller: "CSEReservacionesBundle:Reservacion:envioReservaciones"}
    
reservacion_enviarReporteGanancias:
    pattern: /enviar_reporte_ganancias 
    defaults: {_controller: "CSEReservacionesBundle:Reservacion:envioGanancias"}
