cse_reservaciones_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CSEReservacionesBundle:Default:index }
    
CSEReservacionesBundle_reservacion:
    resource: "@CSEReservacionesBundle/Resources/config/routing/reservacion.yml"
    prefix:   /reservacion
CSEReservacionesBundle_huesped:
    resource: "@CSEReservacionesBundle/Resources/config/routing/huesped.yml"
    prefix:   /huesped
CSEReservacionesBundle_actividad:
        resource: "@CSEReservacionesBundle/Resources/config/routing/actividad.yml"
        prefix:   /actividad
        
principal:
    pattern:  /home
    defaults: { _controller: FrameworkBundle:Template:template, template:  'CSEReservacionesBundle:static:principal.html.twig' }
