parameters:
#    cse_reservaciones.example.class: CSE\ReservacionesBundle\Example

services:
#    cse_reservaciones.example:
#        class: %cse_reservaciones.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
