parameters:
    reservacionesServices.class: CSE\ReservacionesBundle\Services\ReservacionesServices

services:
    reservacionesServices:
        class: %reservacionesServices.class%
        arguments: [@doctrine]
