parameters:
    reservacionesServices.class: CSE\ReservacionesBundle\Services\ReservacionesServices
    enviarEmailServices.class: CSE\ReservacionesBundle\Services\EnviarReservacionServices
    generarReportePDF.class: CSE\ReservacionesBundle\Services\GenerarReportesPdf
    enviarReportesPDF.class: CSE\ReservacionesBundle\Services\EnviarReportesPDF

services:
    reservacionesServices:
        class: %reservacionesServices.class%
        arguments: [@doctrine]
    enviarEmailServices:
        class: %enviarEmailServices.class%
        arguments: [@doctrine, @mailer]
    generarReportePDF:
        class: %generarReportePDF.class%
        arguments: [@doctrine]
    enviarReportePDF:
        class: %enviarReportesPDF.class%
        arguments: [@doctrine, @mailer]