<?php

namespace CSE\ReservacionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadRepository extends EntityRepository {

    public function listarActividades() {

        return $this->getEntityManager()->createQuery("SELECT a.id, a.precio FROM CSEReservacionesBundle:Actividad a")->getResult();
    }
}
