<?php

namespace CSE\ReservacionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtividadesXReservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtividadesXReservacionRepository extends EntityRepository
{
}
