<?php

namespace CSE\ReservacionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HabitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabitacionRepository extends EntityRepository
{
    
    public function consultaPrecios() {
        return $this->getEntityManager()->createQuery("SELECT  h.id, h.precio, h.capacidad FROM CSEReservacionesBundle:Habitacion h ")->getResult();       
    }
}
