<?php

namespace CSE\ReservacionesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\Platforms;

/**
 * ReservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservacionRepository extends EntityRepository {

    public function consultarReservacion($codigo, $cliente) {
        if ($codigo == "") {
            $codigo = null;
        }

        return $this->getEntityManager()->createQuery("SELECT  r FROM CSEReservacionesBundle:Reservacion r JOIN r.huesped h WHERE (r.codigo = :codigo or :codigo is null ) and (h.nombre like :cliente or :cliente is null)")->setParameters(array(
                    'codigo' => $codigo,
                    'cliente' => "%" . $cliente . "%",
                ))->getResult();
    }
    
    public function reporteReservaciones($tipoHabitacion) {
        return $this->getEntityManager()
                ->createQuery("SELECT r FROM CSEReservacionesBundle:Reservacion r JOIN r.habitacion h WHERE h.id = :tipoHabitacion")
                ->setParameter("tipoHabitacion", $tipoHabitacion)->getResult();  
    }
    
    public function  totalReporte($tipoHabitacion){
        return $this->getEntityManager()
                ->createQuery("SELECT SUM(r.totalReservacion + r.subtotalServicios + r.subtotalActividades)AS total FROM CSEReservacionesBundle:Reservacion r JOIN r.habitacion h WHERE h.id = :tipoHabitacion")
                ->setParameter("tipoHabitacion", $tipoHabitacion)->getResult(); 
    }
    
       public function  totalReservaciones(){
        return $this->getEntityManager()
                ->createQuery("SELECT SUM(r.totalReservacion + r.subtotalServicios + r.subtotalActividades)AS total FROM CSEReservacionesBundle:Reservacion r JOIN r.habitacion h")
                ->getResult(); 
    }

}
