<?php

namespace CSE\ReservacionesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\Platforms;

/**
 * ReservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservacionRepository extends EntityRepository {

    public function consultarReservacion($codigo, $cliente) {

        //SELECT * FROM `reservaciones`  r inner join `tipo_habitacion`  th 
        //on r.`tipo_habitacion`=th.capacidad WHERE (r.`idReservacion` like '$pCodigo%') 
        //AND (r.`nombre_completo` like '%$pNombre%' or '%$pNombre%' is null)
        if ($codigo == "") {
            $codigo = null;
        }

        return $this->getEntityManager()->createQuery("SELECT  r FROM CSEReservacionesBundle:Reservacion r JOIN r.huesped h WHERE (r.codigo = :codigo or :codigo is null ) and (h.nombre like :cliente or :cliente is null)")->setParameters(array(
                    'codigo' => $codigo,
                    'cliente' => "%" . $cliente . "%",
                ))->getResult();
    }

}
