<?php

namespace CSE\ReservacionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends EntityRepository
{ 
    public function consultaPrecios() {
        return $this->getEntityManager()->createQuery("SELECT  s.id, s.precio, s.requiereCant FROM CSEReservacionesBundle:Servicio s ")->getResult();       
    }
}
