<?php

namespace CSE\ReservacionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiciosXReservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiciosXReservacionRepository extends EntityRepository
{
    
    public function serviciosXReservacion($id) {
         return $this->getEntityManager()->createQuery("SELECT  sr FROM CSEReservacionesBundle:ServiciosXReservacion sr JOIN sr.reservacion r WHERE r.id = :id ")->setParameter('id', $id)->getResult();
    }
}
